all: dealer hand pitboss
dealer: dealer.o
	g++ -o dealer dealer.o
dealer.o: dealer.cpp
	g++ -c dealer.cpp
hand: hand.o
	g++ -static -L/home/010/j/jc/jca160030/src/lib -o hand  hand.o -lgsl -lgslcblas -lm
hand.o: hand.cpp
	g++ -Wall -I/home/010/j/jc/jca160030/src/include -c hand.cpp
pitboss: pitboss.o
	g++ -o pitboss pitboss.o
pitboss.o: pitboss.cpp
	g++ -c pitboss.cpp
